@baseUrl = http://localhost:3000

### Try to login an unknown user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "newUserName":"unknown",
    "newUserPassword":"unknown"
}

### Create user1
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "newUserEmail":"user1@gmail.com",
    "newUserName":"user1",
    "newUserPassword":"user1",
    "passwordConf":"user1"
}

### Try to login user1 with wrong password
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "newUserName":"user1",
    "newUserPassword":"user100"
}

### Login user1
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "newUserName":"user1",
    "newUserPassword":"user1"
}


### Try to create an user with username already taken
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "newUserEmail":"user2@gmail.com",
    "newUserName":"user1",
    "newUserPassword":"user2",
    "passwordConf":"user2"
}

### Try to create an user with differenct passwords
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "newUserEmail":"user2@gmail.com",
    "newUserName":"user2",
    "newUserPassword":"user2",
    "passwordConf":"user3"
}


### Try to create an user with username already taken
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "newUserEmail":"user5@gmailcom",
    "newUserName":"user5",
    "newUserPassword":"user5",
    "passwordConf":"user5"
}

### Try to create an user with email already taken
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "newUserEmail":"user1@gmail.com",
    "newUserName":"user2",
    "newUserPassword":"user2",
    "passwordConf":"user2"
}

### Delete user 1
DELETE {{baseUrl}}/auths/deleteUser/user1
Content-Type: application/json

### Try to delete unknown user
DELETE {{baseUrl}}/auths/deleteUser/unknown
Content-Type: application/json